### ISSUE TITLE
Regular expression engines

### ISSUE THREAD

**Issue by data-man** [p-ranav/awesome-hpp#45]
[SRELL](http://www.akenotsuki.com/misc/srell/en/) is a template library that has an ECMAScript (JavaScript) compatible regular expression engine wrapped into the same class design as std::regex.
[NIRE](http://www.akenotsuki.com/misc/nire/en/) is a simplified fork of SRELL.

**Comment by data-man** [comment]
I maintain the up-to-date mirror: https://github.com/ZimProjects/SRELL
@p-ranav will you accept PR?

**Comment by p-ranav** [comment]
Sure, go ahead and create a PR.

**Comment by data-man** [comment]
#77
