### ISSUE TITLE
deep learning and matrix calculus

### ISSUE THREAD

**Issue by fengwang** [p-ranav/awesome-hpp#58]
[ceras](https://github.com/fengwang/ceras) is a deep learning engine in C++20;

[matrix](https://github.com/fengwang/matrix) is a 2D matrix lib in C++20.

**Comment by phoebe-leong** [comment]
make a pr on it

**Comment by fengwang** [comment]
@phoebe-leong I have created a [pr](https://github.com/p-ranav/awesome-hpp/pull/68), please kindly review it.
